Add file encoding modeline to setup.py.
This caused the error message when trying to install on Python 2 to
never appear:

SyntaxError: Non-ASCII character '\xc3' in file setup.py on line 17, but
no encoding declared; see http://www.python.org/peps/pep-0263.html for
details